id = "AssetOwner"
icon = "lucide/building-2.svg"
label.en = "Asset Owner"

[[attribute_group]]
id = "markup"
label.en = "Markup"
icon = "lucide/circle-dollar-sign.svg"

[[attribute]]
id = "label"
label.en = "Label"
tooltip.en = "Label of the asset owner"

[[attribute]]
id = "price_type"
label.en = "Price Type"
tooltip.en = "Price type of the asset owner"