id = "AssetOwner"
icon = "lucide/user-round.svg"
label.en = "AssetOwner"

[[card]]
query = """
SELECT 
  CASE 
    WHEN COUNT(*) = 0 THEN 'inactive'
    ELSE 'active'
  END
FROM AssetOwner;
"""
type = "string"
label.en = "Status"

[[card]]
query = "SELECT COUNT(*) FROM AssetOwner"
type = "integer"
label.en = "Elements"
unit.en = "AssetOwner(s)"

[[attribute]]
id = "label"
label.en = "Label"
tooltip.en = "Name of the branch"

[[attribute]]
id = "is_price_maker"
label.en = "Price Maker"
tooltip.en = "Price maker asset owner"
type = "enum"
enum = "bool"

[[attribute]]
id = "quantity_offer"
label.en = "Quantity Offer"
tooltip.en = "Name of the quantity offer time series file"

[[attribute]]
id = "price_offer"
label.en = "Price Offer"
tooltip.en = "Name of the price offer time series file"
