id = "Battery"
icon = "lucide/battery-medium.svg"
label.en = "Battery"

[[card]]
query = """
SELECT 
  CASE 
    WHEN COUNT(*) = 0 THEN 'inactive'
    ELSE 'active'
  END
FROM Battery;
"""
type = "string"
label.en = "Status"

[[card]]
query = "SELECT COUNT(*) FROM Battery"
type = "integer"
label.en = "Elements"
unit.en = "Battery(ies)"

[[attribute_group]]
id = "parameters"
label.en = "Parameters"
icon = "lucide/log-in.svg"

[[attribute]]
id = "label"
label.en = "Label"
tooltip.en = "Name of the battery"

[[attribute]]
id = "date_time"
label.en = "Date Time"
tooltip.en = "Date and time"
format = "yyyy-MM-dd HH:mm"
unit = "yyyy-MM-dd HH:mm"

[[attribute]]
id = "existing"
label.en = "Existing"
tooltip.en = "Indicates if the battery is already installed in the system"
type = "enum"
enum = "bool"
hide = true

[[attribute]]
id = "initial_storage"
label.en = "Initial Storage"
tooltip.en = "Initial storage of the battery"
unit.en = "MWh"
hide = true

[[attribute]]
id = "min_storage"
label.en = "Min storage"
tooltip.en = "Minimum Storage"
unit.en = "MWh"
hide = true

[[attribute]]
id = "max_storage"
label.en = "Max storage"
tooltip.en = "Maximum Storage"
unit.en = "MWh"

[[attribute]]
id = "max_capacity"
label.en = "Max capacity"
tooltip.en = "Maximum Capacity"
unit.en = "MW"

[[attribute]]
id = "om_cost"
label.en = "O&M Cost"
tooltip.en = "Operation and maintenance cost"
unit.en = "$/MWh"
hide = true

[[attribute]]
id = "bus_id"
label.en = "Bus"
tooltip.en = "Bus"

[[attribute]]
id = "assetowner_id"
label.en = "AssetOwner"
tooltip.en = "AssetOwner"
