id = "Branch"
icon = "lucide/git-branch.svg"
label.en = "Branch"

[[card]]
query = "SELECT COUNT(*) FROM Branch"
type = "integer"
label.en = "Elements"
unit.en = "branch(es)"

[[attribute]]
id = "label"
label.en = "Label"
tooltip.en = "Label of the branch"

[[attribute]]
id = "line_model"
label.en = "Line Model"
tooltip.en = "Line model of the branch"

[[attribute]]
id = "bus_to"
label.en = "Bus To"
tooltip.en = "Bus to of the branch"

[[attribute]]
id = "bus_from"
label.en = "Bus From"
tooltip.en = "Bus from of the branch"

[[attribute_group]]
id = "parameters"
label.en = "Parameters"
icon = "lucide/settings-2.svg"

[[attribute]]
id = "date_time"
label.en = "Date Time"
tooltip.en = "Date time of the branch"

[[attribute]]
id = "existing"
type = "enum"
enum = "existing"
label.en = "Existing"
tooltip.en = "Existing of the branch"

[[attribute]]
id = "capacity"
label.en = "Capacity"
tooltip.en = "Capacity of the branch"

[[attribute]]
id = "reactance"
label.en = "Reactance"
tooltip.en = "Reactance of the branch"
