id = "Branch"
icon = "lucide/minus.svg"
label.en = "Branch"

[[attribute_group]]
id = "parameters"
label.en = "Parameters"
icon = "lucide/settings-2.svg"

[[attribute]]
id = "label"
label.en = "Label"
tooltip.en = "Label of the branch"

[[attribute]]
id = "line_model"
label.en = "Line Model"
tooltip.en = "Line model of the branch"

[[attribute]]
id = "bus_to"
label.en = "Bus To"
tooltip.en = "Bus to of the branch"

[[attribute]]
id = "bus_from"
label.en = "Bus From"
tooltip.en = "Bus from of the branch"
