id = "Bus"
icon = "lucide/waypoints.svg"
label.en = "Bus"

[[card]]
query = """
SELECT 
  CASE 
    WHEN COUNT(*) = 0 THEN 'inactive'
    ELSE 'active'
  END
FROM Bus;
"""
type = "string"
label.en = "Status"

[[card]]
query = "SELECT COUNT(*) FROM Bus"
type = "integer"
label.en = "Elements"
unit.en = "Bus(es)"

[[attribute]]
id = "label"
label.en = "Label"
tooltip.en = "Name of the bus"

[[attribute]]
id = "zone_id"
label.en = "Zone"
tooltip.en = "Name of the zone"
