id = "DCLine"
icon = "lucide/spline.svg"
label.en = "DC Line"

[[attribute_group]]
id = "parameters"
label.en = "Parameters"
icon = "lucide/settings-2.svg"

[[attribute]]
id = "label"
label.en = "Label"
tooltip.en = "Label of the DC line"

[[attribute]]
id = "bus_to"
label.en = "Bus To"
tooltip.en = "Bus to of the DC line"

[[attribute]]
id = "bus_from"
label.en = "Bus From"
tooltip.en = "Bus from of the DC line"