id = "DCLine"
icon = "lucide/spline.svg"
label.en = "DC Line"

[[card]]
query = "SELECT COUNT(*) FROM DCLine"
type = "integer"
label.en = "Elements"
unit.en = "DC line(s)"

[[attribute]]
id = "label"
label.en = "Label"
tooltip.en = "Label of the DC line"

[[attribute]]
id = "bus_to"
label.en = "Bus To"
tooltip.en = "Bus to of the DC line"

[[attribute]]
id = "bus_from"
label.en = "Bus From"
tooltip.en = "Bus from of the DC line"

[[attribute_group]]
id = "parameters"
label.en = "Parameters"
icon = "lucide/settings-2.svg"

[[attribute]]
id = "date_time"
label.en = "Date Time"
tooltip.en = "Date time of the DC line"
unit = "yyyy-MM-dd HH:mm"

[[attribute]]
id = "existing"
type = "enum"
enum = "existing"
label.en = "Existing"
tooltip.en = "Existing of the DC line"

[[attribute]]
id = "capacity_to"
label.en = "Capacity To"
tooltip.en = "Capacity to of the DC line"

[[attribute]]
id = "capacity_from"
label.en = "Capacity From"
tooltip.en = "Capacity from of the DC line"
