id = "DemandUnit"
icon = "lucide/zap.svg"
label.en = "Demand Unit"

[[card]]
query = "SELECT COUNT(*) FROM DemandUnit"
type = "integer"
label.en = "Elements"
unit.en = "demand unit(s)"

[[card]]
query = "SELECT COUNT(*) FROM DemandUnit_time_series_parameters"
type = "integer"
label.en = "Modifications"
unit.en = "records"

[[attribute]]
id = "label"
label.en = "Label"
tooltip.en = "Label of the demand unit"

[[attribute]]
id = "demand_unit_type"
label.en = "Demand Unit Type"
tooltip.en = "Demand unit type of the demand unit"

[[attribute]]
id = "max_shift_up"
label.en = "Max Shift Up"
tooltip.en = "Max shift up of the demand unit"

[[attribute]]
id = "max_shift_down"
label.en = "Max Shift Down"
tooltip.en = "Max shift down of the demand unit"

[[attribute]]
id = "curtailment_cost"
label.en = "Curtailment Cost"
tooltip.en = "Curtailment cost of the demand unit"

[[attribute]]
id = "max_curtailment"
label.en = "Max Curtailment"
tooltip.en = "Max curtailment of the demand unit"

[[attribute]]
id = "bus_id"
label.en = "Bus"
tooltip.en = "Bus of the demand unit"

[[attribute]]
id = "max_demand"
label.en = "Max Demand"
tooltip.en = "Max demand of the demand unit"

[[attribute]]
id = "gaugingstation_downstream"
label.en = "Gauging Station Downstream"
tooltip.en = "Gauging station downstream of the demand unit"

[[attribute_group]]
id = "parameters"
label.en = "Parameters"
icon = "lucide/settings-2.svg"

[[attribute]]
id = "date_time"
label.en = "Date Time"
tooltip.en = "Date time of the demand unit"

[[attribute]]
id = "existing"
type = "enum"
enum = "existing"
label.en = "Existing"
tooltip.en = "Existing of the demand unit"
