id = "GaugingStation"
icon = "lucide/gauge.svg"
label.en = "Gauging Station"

[[attribute]]
id = "label"
label.en = "Label"
tooltip.en = "Label of the gauging station"

[[attribute]]
id = "gaugingstation_downstream"
label.en = "Gauging Station Downstream"
tooltip.en = "Gauging station downstream of the gauging station"

[[attribute_group]]
id = "historical_inflow"
label.en = "Historical Inflow"
icon = "lucide/chart-spline.svg"

[[attribute]]
id = "date_time"
label.en = "Date Time"
tooltip.en = "Date time of the gauging station"

[[attribute]]
id = "historical_inflow"
label.en = "Historical Inflow"
tooltip.en = "Historical inflow of the gauging station"
