id = "HydroUnit"
icon = "lucide/dam.svg"
label.en = "Hydro Unit"

[[card]]
query = "SELECT COUNT(*) FROM HydroUnit"
type = "integer"
label.en = "Elements"
unit.en = "hydro unit(s)"

[[attribute]]
id = "label"
label.en = "Label"
tooltip.en = "Label of the hydro unit"

[[attribute]]
id = "initial_volume"
label.en = "Initial Volume"
tooltip.en = "Initial volume of the hydro unit"

[[attribute]]
id = "initial_volume_type"
label.en = "Initial Volume Type"
tooltip.en = "Initial volume type of the hydro unit"

[[attribute]]
id = "has_commitment"
type = "enum"
enum = "has_commitment"
label.en = "Has Commitment"
tooltip.en = "Has commitment of the hydro unit"

[[attribute]]
id = "operation_type"
label.en = "Operation Type"
tooltip.en = "Operation type of the hydro unit"

[[attribute]]
id = "bus_id"
label.en = "Bus"
tooltip.en = "Bus of the hydro unit"

[[attribute]]
id = "biddinggroup_id"
label.en = "Bidding Group"
tooltip.en = "Bidding group of the hydro unit"

[[attribute]]
id = "gaugingstation_id"
label.en = "Gauging Station"
tooltip.en = "Gauging station of the hydro unit"

[[attribute]]
id = "hydrounit_turbine_to"
label.en = "Turbine To"
tooltip.en = "Turbine to of the hydro unit"

[[attribute]]
id = "hydrounit_spill_to"
label.en = "Spill To"
tooltip.en = "Spill to of the hydro unit"

[[attribute_group]]
id = "waveguide"
label.en = "Waveguide"
icon = "lucide/settings-2.svg"

[[attribute]]
id = "waveguide_volume"
label.en = "Waveguide Volume"
tooltip.en = "Waveguide volume of the hydro unit"

[[attribute_group]]
id = "parameters"
label.en = "Parameters"
icon = "lucide/settings-2.svg"

[[attribute]]
id = "date_time"
label.en = "Date Time"
tooltip.en = "Date time of the hydro unit"

[[attribute]]
id = "existing"
type = "enum"
enum = "existing"
label.en = "Existing"
tooltip.en = "Existing of the hydro unit"

[[attribute]]
id = "production_factor"
label.en = "Production Factor"
tooltip.en = "Production factor of the hydro unit"

[[attribute]]
id = "min_generation"
label.en = "Min Generation"
tooltip.en = "Min generation of the hydro unit"

[[attribute]]
id = "max_generation"
label.en = "Max Generation"
tooltip.en = "Max generation of the hydro unit"

[[attribute]]
id = "max_turbining"
label.en = "Max Turbining"
tooltip.en = "Max turbining of the hydro unit"

[[attribute]]
id = "min_volume"
label.en = "Min Volume"
tooltip.en = "Min volume of the hydro unit"

[[attribute]]
id = "max_volume"
label.en = "Max Volume"
tooltip.en = "Max volume of the hydro unit"

[[attribute]]
id = "min_outflow"
label.en = "Min Outflow"
tooltip.en = "Min outflow of the hydro unit"

[[attribute]]
id = "om_cost"
label.en = "O&M Cost"
tooltip.en = "O&M cost of the hydro unit"
