id = "HydroPlant"
icon = "lucide/waves.svg"
label.en = "Hydro Plant"

[[card]]
query = """
SELECT 
  CASE 
    WHEN COUNT(*) = 0 THEN 'inactive'
    ELSE 'active'
  END
FROM HydroPlant;
"""
type = "string"
label.en = "Status"

[[card]]
query = "SELECT COUNT(*) FROM HydroPlant"
type = "integer"
label.en = "Elements"
unit.en = "Hydro plant(s)"

[[attribute_group]]
id = "parameters"
label.en = "Parameters"
icon = "lucide/log-in.svg"

[[attribute_group]]
id = "om_cost"
label.en = "O&M Cost"
icon = "lucide/log-in.svg"

[[attribute]]
id = "date_time"
label.en = "Date Time"
tooltip.en = "Date and time"
format = "yyyy-MM-dd HH:mm"
unit = "yyyy-MM-dd HH:mm"

[[attribute]]
id = "label"
label.en = "Label"
tooltip.en = "Name of the hydro plant"

[[attribute]]
id = "existing"
label.en = "Existing"
tooltip.en = "Whether the hydro plant is existing or future"
type = "enum"
enum = "bool"
hide = true

[[attribute]]
id = "min_generation"
label.en = "Minimum Generation"
tooltip.en = "Minimum generation of the hydro plant"
unit.en = "MW"
hide = true

[[attribute]]
id = "max_generation"
label.en = "Maximum Generation"
tooltip.en = "Maximum generation of the hydro plant"
unit.en = "MW"

[[attribute]]
id = "production_factor"
label.en = "Production Factor"
tooltip.en = "Production factor of the hydro plant"
unit.en = "MW/m³/s"
hide = true

[[attribute]]
id = "max_turbining"
label.en = "Maximum Turbining"
tooltip.en = "Maximum turbining of the hydro plant"
unit.en = "m³/s"
hide = true

[[attribute]]
id = "min_volume"
label.en = "Minimum Volume"
tooltip.en = "Minimum volume of the hydro plant"
unit.en = "hm³"

[[attribute]]
id = "max_volume"
label.en = "Maximum Volume"
tooltip.en = "Maximum volume of the hydro plant"
unit.en = "hm³"

[[attribute]]
id = "initial_volume"
label.en = "Initial Volume"
tooltip.en = "Initial volume of the hydro plant"
unit.en = "hm³"
hide = true

[[attribute]]
id = "initial_volume_type"
label.en = "Initial Volume"
type = "enum"
enum = "hydro_initial_volume_type"
tooltip.en = "Type of the initial volume"
hide = true

[[attribute]]
id = "min_outflow"
label.en = "Minimum Outflow"
tooltip.en = "Minimum outflow of the hydro plant"
unit.en = "m³/s"
hide = true

[[attribute]]
id = "om_cost"
label.en = "O&M Cost"
tooltip.en = "Operation and maintenance cost of the hydro plant"
unit.en = "$/MWh"
hide = true

[[attribute]]
id = "has_commitment"
label.en = "Has Commitment"
tooltip.en = "Whether the hydro plant has commitment"
type = "enum"
enum = "bool"
hide = true

[[attribute]]
id = "inflow"
label.en = "Inflow"
tooltip.en = "Inflow file name"
hide = true

[[attribute]]
id = "bus_id"
label.en = "Bus"
tooltip.en = "Bus"

[[attribute]]
id = "assetowner_id"
label.en = "AssetOwner"
tooltip.en = "AssetOwner"

[[attribute]]
id = "hydroplant_turbine_to"
label.en = "Turbining To"
tooltip.en = "Downstream plant for turbining"

[[attribute]]
id = "hydroplant_spill_to"
label.en = "Spillage To"
tooltip.en = "Downstream plant for spillage"

[[attribute]]
id = "gaugingstation_id"
label.en = "Gauging Station"
tooltip.en = "Gauging station of the hydro plant"