model = "IARA"
extension = "iara"
executable = "IARA.bat"
dashboard = "results/iara_dashboard_summarized.html"
documentation = "index.html"
collections = [
    "configuration",
    "asset_owner",
    "battery_unit",
    "bidding_group",
    "branch",
    "bus",
    "dc_line",
    "demand_unit",
    "gauging_station",
    "hydro_unit",
    "interconnection",
    "main",
    "renewable_unit",
    "thermal_unit",
    "virtual_reservoir",
    "zone",
]
