id = "RenewableUnit"
icon = "lucide/sun.svg"
label.en = "Renewable Unit"

[[card]]
query = "SELECT COUNT(*) FROM RenewableUnit"
type = "integer"
label.en = "Elements"
unit.en = "renewable unit(s)"

[[attribute]]
id = "label"
label.en = "Label"
tooltip.en = "Label of the renewable unit"

[[attribute]]
id = "technology_type"
label.en = "Technology Type"
tooltip.en = "Technology type of the renewable unit"

[[attribute]]
id = "bus_id"
label.en = "Bus"
tooltip.en = "Bus of the renewable unit"

[[attribute]]
id = "biddinggroup_id"
label.en = "Bidding Group"
tooltip.en = "Bidding group of the renewable unit"

[[attribute_group]]
id = "parameters"
label.en = "Parameters"
icon = "lucide/settings-2.svg"

[[attribute]]
id = "date_time"
label.en = "Date Time"
tooltip.en = "Date time of the renewable unit"
unit = "yyyy-MM-dd HH:mm"

[[attribute]]
id = "existing"
type = "enum"
enum = "existing"
label.en = "Existing"
tooltip.en = "Existing of the renewable unit"

[[attribute]]
id = "max_generation"
label.en = "Max Generation"
tooltip.en = "Max generation of the renewable unit"

[[attribute]]
id = "om_cost"
label.en = "O&M Cost"
tooltip.en = "O&M cost of the renewable unit"

[[attribute]]
id = "curtailment_cost"
label.en = "Curtailment Cost"
tooltip.en = "Curtailment cost of the renewable unit"
