id = "ThermalUnit"
icon = "lucide/factory.svg"
label.en = "Thermal Unit"

[[card]]
query = "SELECT COUNT(*) FROM ThermalUnit"
type = "integer"
label.en = "Elements"
unit.en = "thermal unit(s)"

[[attribute]]
id = "label"
label.en = "Label"
tooltip.en = "Label of the thermal unit"

[[attribute]]
id = "has_commitment"
type = "enum"
enum = "has_commitment"
label.en = "Has Commitment"
tooltip.en = "Has commitment of the thermal unit"

[[attribute]]
id = "max_ramp_up"
label.en = "Max Ramp Up"
tooltip.en = "Max ramp up of the thermal unit"

[[attribute]]
id = "max_ramp_down"
label.en = "Max Ramp Down"
tooltip.en = "Max ramp down of the thermal unit"

[[attribute]]
id = "min_uptime"
label.en = "Min Uptime"
tooltip.en = "Min uptime of the thermal unit"

[[attribute]]
id = "max_uptime"
label.en = "Max Uptime"
tooltip.en = "Max uptime of the thermal unit"

[[attribute]]
id = "min_downtime"
label.en = "Min Downtime"
tooltip.en = "Min downtime of the thermal unit"

[[attribute]]
id = "max_startups"
label.en = "Max Startups"
tooltip.en = "Max startups of the thermal unit"

[[attribute]]
id = "max_shutdowns"
label.en = "Max Shutdowns"
tooltip.en = "Max shutdowns of the thermal unit"

[[attribute]]
id = "shutdown_cost"
label.en = "Shutdown Cost"
tooltip.en = "Shutdown cost of the thermal unit"

[[attribute]]
id = "generation_initial_condition"
label.en = "Generation Initial Condition"
tooltip.en = "Generation initial condition of the thermal unit"

[[attribute]]
id = "uptime_initial_condition"
label.en = "Uptime Initial Condition"
tooltip.en = "Uptime initial condition of the thermal unit"

[[attribute]]
id = "downtime_initial_condition"
label.en = "Downtime Initial Condition"
tooltip.en = "Downtime initial condition of the thermal unit"

[[attribute]]
id = "bus_id"
label.en = "Bus"
tooltip.en = "Bus of the thermal unit"

[[attribute]]
id = "biddinggroup_id"
label.en = "Bidding Group"
tooltip.en = "Bidding group of the thermal unit"

[[attribute]]
id = "commitment_initial_condition"
type = "enum"
enum = "commitment_initial_condition"
label.en = "Commitment Initial Condition"
tooltip.en = "Commitment initial condition of the thermal unit"

[[attribute_group]]
id = "parameters"
label.en = "Parameters"
icon = "lucide/settings-2.svg"

[[attribute]]
id = "date_time"
label.en = "Date Time"
tooltip.en = "Date time of the thermal unit"
unit = "yyyy-MM-dd HH:mm"

[[attribute]]
id = "existing"
type = "enum"
enum = "existing"
label.en = "Existing"
tooltip.en = "Existing of the thermal unit"

[[attribute]]
id = "startup_cost"
label.en = "Startup Cost"
tooltip.en = "Startup cost of the thermal unit"

[[attribute]]
id = "min_generation"
label.en = "Min Generation"
tooltip.en = "Min generation of the thermal unit"

[[attribute]]
id = "max_generation"
label.en = "Max Generation"
tooltip.en = "Max generation of the thermal unit"

[[attribute]]
id = "om_cost"
label.en = "O&M Cost"
tooltip.en = "O&M cost of the thermal unit"
