id = "VirtualReservoir"
icon = "lucide/droplet.svg"
label.en = "Virtual Reservoir"

[[attribute]]
id = "label"
label.en = "Label"
tooltip.en = "Label of the virtual reservoir"

[[attribute]]
id = "number_of_waveguide_points_for_file_template"
label.en = "Number of Waveguide Points for File Template"
tooltip.en = "Number of waveguide points for file template of the virtual reservoir"